'use strict';

module.exports = {
    storeRating               : '#feedback-summary > div.middle.middle-seller > table > tbody > tr:nth-child(2) > td > span',
    feedBackStoreFrame        : '#detail-displayer',
    email                     : '#fm-login-id',
    password                  : '#fm-login-password',
    signin                    : '#login-form > div.fm-btn > button',
    loginFrame                : '#alibaba-login-box',
    modalClosefirst           : 'a.close-layer[data-role="layer-close"]',
    modalCloseSecond          : 'a.next-dialog-close[aria-label="关闭"]',
    switcher                  : '#switcher-info',
    flagIcon                  : '#switcher-info > .ship-to i.css_us',
    country                   : 'a[data-role="country"]',
    usCode                    : 'ul.address-select-content li[data-code="us"]',
    saveShipping              : 'button[data-role="save"]',
    productList               : 'ul.items-list',
    paginationOverallCount    : '#pagination-bottom > .ui-pagination-navi > a:nth-last-child(2)',
    nextPage                  : '#pagination-bottom .ui-pagination-active + a',
    productItem               : 'ul.items-list.util-clearfix > li.item > .detail > h3 a',
    availableItems            : '.sku-property-list > .sku-property-item:not(.disabled) > .sku-property-image img',
    availableItems2           : '.sku-property-list > .sku-property-item:not(.disabled) > .sku-property-color span',
    skuTitle                  : '.product-sku .sku-property:nth-child(1) .sku-title',
    skuTitles                 : '.product-sku .sku-property > .sku-title',
    skuTitleValue             : '.product-sku .sku-property:nth-child(1) .sku-title > .sku-title-value',
    skuTitleValue2            : '.product-sku .sku-property:nth-child(2) .sku-title > .sku-title-value',
    productTitle              : '.product-info > .product-title',
    productSizes              : 'div.product-info > div.product-sku > div > div:nth-child(2) > ul.sku-property-list > li.sku-property-item:not(.disabled) .sku-property-text',
    productRating             : 'span[itemprop="ratingValue"]',
    productOrders             : '.product-reviewer .product-reviewer-sold',
    productDesc               : '.product-overview > #product-description > .origin-part.box-sizing',
    productDiscountedPrice    : 'span[itemprop="price"]',
    productOriginalPrice      : '.product-price-original .product-price-del .product-price-value',
    productStocks             : '.product-quantity-tip span',
    productLikes              : 'span.add-wishlist-num',
    productMainImage          : '.product-main-wrap .img-view-wrap .image-viewer .image-view-magnifier-wrap img',
    productFeaturedImages     : '.image-viewer .images-view-wrap .images-view-list > li:not(.active) img',
    productOverviewTab        : '#product-detail ul.tab-lists > li[ae_button_type="tab_prodetail"] > .tab-inner',
    specificationTab          : '#product-detail ul.tab-lists > li[ae_button_type="tab_specs"] > .tab-inner',
    specWrapper               : '#product-detail .product-specs',
    specificationItems        : '.product-specs ul.product-specs-list > li',
    feedbackTabText           : '#product-detail li[ae_button_type="tab_feedback"]',
    feedbackTabInner          : '#product-detail ul.tab-lists > li[ae_button_type="tab_feedback"] > .tab-inner',
    feedBackWrapper           : '.feedback-list-wrap',
    productEvaluationFrame    : '#product-evaluation',
    productFeedbackDropdown   : '#transction-feedback > div.filter-wrap.clearfix > div.f-star-dropdown > span',
    productPositiveOption     : '#filter_star_list ul > li  a[data="All positive"]',
    productPositiveCount      : '#transction-feedback > .filter-wrap > .f-star-dropdown > .fb-star-selector em',
    productFeedbackPhotoOption: '#transction-feedback > .filter-wrap > .f-filter-list > label',
    productFeedbackPageWrapper: '#complex-pager',
    productFeedBackWrapper    : '#transction-feedback > .feedback-list-wrap > .feedback-item > .fb-main',
    reviewRating              : '.f-rate-info .star-view span',
    reviewSKU                 : '.user-order-info > span.first strong',
    reviewComment             : '.f-content dt.buyer-feedback span:first-child',
    reviewDate                : '.f-content dt.buyer-feedback span.r-time-new',
    reviewImageWrapper        : '.f-content dd[data-role="photo-list"]',
    reviewImages              : '.f-content dd[data-role="photo-list"] > ul.util-clearfix > li > img',
    productOverview           : '#product-description',
};
